CREATE TABLE films (
    id int PRIMARY KEY AUTO_INCREMENT NOT NULL,
    name varchar(200),
    description varchar(200),
    release_date date,
    duration int,
    rating int,
    director int
);

CREATE TABLE users (
    id int PRIMARY KEY AUTO_INCREMENT NOT NULL,
    name varchar(200) NOT NULL,
    login varchar(200) NOT NULL,
    email varchar(200) NOT NULL,
    birthday date
);

CREATE TABLE ratings (
    id int PRIMARY KEY AUTO_INCREMENT NOT NULL,
    name varchar(200)
);

CREATE TABLE genres (
    id int PRIMARY KEY AUTO_INCREMENT NOT NULL,
    name varchar(200)
);

CREATE TABLE film_genre (
    film_id int NOT NULL,
    genre_id int NOT NULL,
    PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE film_like (
    film_id int NOT NULL,
    user_id int NOT NULL,
    PRIMARY KEY (film_id, user_id)
);

CREATE TABLE film_feedback (
    film_id int NOT NULL,
    user_id int NOT NULL,
    feedback varchar(500),
    PRIMARY KEY (film_id, user_id)
);

CREATE TABLE friends (
    user_id int NOT NULL,
    friend_id int NOT NULL,
    status boolean,
    PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE events (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp numeric,
    operation varchar(20),
    event_type varchar(20),
    user_id integer NOT NULL,
    entity_id integer NOT NULL
);

CREATE TABLE reviews (
    id int PRIMARY KEY AUTO_INCREMENT NOT NULL,
    content varchar(500) NOT NULL,
    is_positive boolean NOT NULL,
    user_id int NOT NULL,
    film_id int NOT NULL
);

CREATE TABLE review_like (
    review_id int NOT NULL,
    user_id int NOT NULL,
    useful int NOT NULL,
    PRIMARY KEY (review_id, user_id)
);

CREATE TABLE directors (
    id int PRIMARY KEY AUTO_INCREMENT NOT NULL,
    name varchar(200) NOT NULL
);

CREATE TABLE film_director (
   film_id int NOT NULL,
   director_id int NOT NULL,
   PRIMARY KEY (film_id, director_id)
);

ALTER TABLE film_genre ADD CONSTRAINT fk_film_id FOREIGN KEY(film_id) REFERENCES films(id) ON DELETE CASCADE;
ALTER TABLE film_genre ADD CONSTRAINT fk_genre_id FOREIGN KEY(genre_id) REFERENCES genres(id) ON DELETE CASCADE;

ALTER TABLE film_like ADD CONSTRAINT fk_film_id_like FOREIGN KEY(film_id) REFERENCES films(id) ON DELETE CASCADE;
ALTER TABLE film_like ADD CONSTRAINT fk_user_id_like FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE friends ADD CONSTRAINT fk_user_id FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE friends ADD CONSTRAINT fk_friend_id FOREIGN KEY(friend_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE film_feedback ADD CONSTRAINT fk_film_fb_id FOREIGN KEY(film_id) REFERENCES films(id) ON DELETE CASCADE;
ALTER TABLE film_feedback ADD CONSTRAINT fk_user_fb_id FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE reviews ADD CONSTRAINT fk_rev_film_id FOREIGN KEY(film_id) REFERENCES films(id) ON DELETE CASCADE;
ALTER TABLE reviews ADD CONSTRAINT fk_rev_user_id FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE film_director ADD CONSTRAINT fd_film_id FOREIGN KEY(film_id) REFERENCES films(id) ON DELETE CASCADE;
ALTER TABLE film_director ADD CONSTRAINT fd_director_id FOREIGN KEY(director_id) REFERENCES directors(id) ON DELETE CASCADE;

ALTER TABLE review_like ADD CONSTRAINT fk_rl_rev_id FOREIGN KEY(review_id) REFERENCES reviews(id) ON DELETE CASCADE;
ALTER TABLE review_like ADD CONSTRAINT fk_rl_user_id FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE events ADD CONSTRAINT fk_ev_user_id FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE;
